import Head from 'next/head'

export default function Home() {
  return (
    <div className="home">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next             app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <h1>Hello Next World </h1>
      </main>
    </div>
  )
}
